name: ðŸ”„ Sync All Workflows to Local Workspace

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/**'
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours

jobs:
  sync-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸ“¥ Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.UPLOAD_PATH }}

      - name: ðŸ”„ Create Workflow Sync Directory
        run: |
          mkdir -p workflow-sync/github-actions
          mkdir -p workflow-sync/mcp-configs
          mkdir -p workflow-sync/scripts
          mkdir -p workflow-sync/docs

      - name: ðŸ“‹ Copy All GitHub Actions Workflows
        run: |
          echo "ðŸ”„ Syncing GitHub Actions workflows..."
          cp -r .github/workflows/* workflow-sync/github-actions/
          
          # Create index of all workflows
          echo "# GitHub Actions Workflows Index" > workflow-sync/github-actions/README.md
          echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> workflow-sync/github-actions/README.md
          echo "" >> workflow-sync/github-actions/README.md
          
          for file in .github/workflows/*.yml; do
            if [[ -f "$file" ]]; then
              filename=$(basename "$file")
              echo "- [$filename](./$filename)" >> workflow-sync/github-actions/README.md
            fi
          done

      - name: ðŸ“‹ Copy MCP Configurations
        run: |
          echo "ðŸ”„ Syncing MCP configurations..."
          
          # Copy project MCP configs
          if [[ -f ".qodo/mcp_config.json" ]]; then
            cp .qodo/mcp_config.json workflow-sync/mcp-configs/project-mcp-config.json
          fi
          
          # Copy shared services
          if [[ -d "shared/services" ]]; then
            cp -r shared/services workflow-sync/mcp-configs/
          fi
          
          # Create MCP index
          echo "# MCP Configurations Index" > workflow-sync/mcp-configs/README.md
          echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> workflow-sync/mcp-configs/README.md
          echo "" >> workflow-sync/mcp-configs/README.md
          echo "- [Project MCP Config](./project-mcp-config.json)" >> workflow-sync/mcp-configs/README.md
          echo "- [Shared Services](./services/)" >> workflow-sync/mcp-configs/README.md

      - name: ðŸ“‹ Copy Scripts
        run: |
          echo "ðŸ”„ Syncing scripts..."
          
          if [[ -d "scripts" ]]; then
            cp -r scripts/* workflow-sync/scripts/
          fi
          
          # Create scripts index
          echo "# Scripts Index" > workflow-sync/scripts/README.md
          echo "Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> workflow-sync/scripts/README.md
          echo "" >> workflow-sync/scripts/README.md
          
          for file in scripts/*; do
            if [[ -f "$file" ]]; then
              filename=$(basename "$file")
              echo "- [$filename](./$filename)" >> workflow-sync/scripts/README.md
            fi
          done

      - name: ðŸ“‹ Create Documentation
        run: |
          echo "ðŸ”„ Creating documentation..."
          
          # Main README
          cat > workflow-sync/README.md << 'EOF'
          # Multi-Hub Workflow Sync
          
          This directory contains synchronized copies of all GitHub Actions workflows, MCP configurations, and scripts from the Multi-Hub project.
          
          ## Structure
          
          - `github-actions/` - All GitHub Actions workflow files
          - `mcp-configs/` - MCP server configurations and services
          - `scripts/` - Automation and setup scripts
          - `docs/` - Generated documentation
          
          ## Usage
          
          1. Pull this repository with GitHub Desktop
          2. All workflows are automatically synced every 6 hours
          3. Manual sync available via workflow dispatch
          
          ## Last Updated
          
          EOF
          
          echo "$(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> workflow-sync/README.md
          
          # Create deployment info
          cat > workflow-sync/deployment-info.json << EOF
          {
            "syncedAt": "$(date -u '+%Y-%m-%dT%H:%M:%SZ')",
            "gitCommit": "$GITHUB_SHA",
            "workflowRun": "$GITHUB_RUN_ID",
            "repository": "Alot1z/multi-hub-project",
            "syncType": "automated"
          }
          EOF

      - name: ðŸ’¾ Commit Synced Files
        run: |
          git config user.name "Workflow Sync Bot"
          git config user.email "sync-bot@alot1z.github.io"
          
          git add workflow-sync/
          
          if git diff --staged --quiet; then
            echo "â„¹ï¸ No workflow changes to sync"
          else
            git commit -m "ðŸ”„ Auto-sync workflows and configs - $(date -u '+%Y-%m-%d %H:%M:%S UTC')

          âœ… GitHub Actions workflows synced
          âœ… MCP configurations synced  
          âœ… Scripts synced
          âœ… Documentation updated
          
          Commit: $GITHUB_SHA
          Run: $GITHUB_RUN_ID"
            
            git push origin main
            echo "âœ… Workflow sync completed and pushed"
          fi

      - name: ðŸ“Š Sync Summary
        run: |
          echo "ðŸŽ‰ WORKFLOW SYNC COMPLETE!"
          echo "=========================="
          echo "ðŸ“ Synced to: workflow-sync/"
          echo "ðŸ”„ GitHub Actions: $(ls -1 .github/workflows/*.yml | wc -l) files"
          echo "âš™ï¸ MCP Configs: $(find .qodo shared/services -name "*.json" -o -name "*.js" 2>/dev/null | wc -l) files"
          echo "ðŸ“œ Scripts: $(ls -1 scripts/* 2>/dev/null | wc -l) files"
          echo ""
          echo "ðŸ”— Access via GitHub Desktop:"
          echo "1. Pull latest changes"
          echo "2. Navigate to workflow-sync/ directory"
          echo "3. All files are ready for local editing"
          echo ""
          echo "ðŸŽ¯ Next sync: Automatic in 6 hours"
